# -*- coding: utf-8 -*-
"""ONLINE SALES BASIC ANALYSIS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIUdvgwh4DLxyyExglgl1wLAtNXiQD2H
"""

import numpy as np
import pandas as pd
import  matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv(r'/content/Online Shop Customer Sales Data.csv')
pd.set_option('display.max_columns',None)

df.dtypes

df.shape

df.size

df.isnull().sum()

df['Purchase_DATE']=pd.to_datetime(df['Purchase_DATE'],format='%d.%m.%y')

"""# Converting Numerical Values To Categorical Values

Gender = 0: Male, 1: Female
Pay_Method = 0: Digital Wallets, 1: Card, 2: PayPal, 3: Other
Browser = 0: Chrome, 1: Safari, 2: Edge, 3: Other
Newsletter = 0: not subscribed, 1: subscribed
Voucher = 0: not used, 1: used
"""

df.head(5)

df.loc[df['Gender']==0,'Gender']='Male'
df.loc[df['Gender']==1,'Gender']='Female'
df.loc[df['Voucher']==0,'Voucher']='Not used'
df.loc[df['Voucher']==1,'Voucher']='used'
df.loc[df['Newsletter']==0,'Newsletter']='not subscribed'
df.loc[df['Newsletter']==1,'Newsletter']='subscribed'

def paymethod(v):
    d={0: 'Digital Wallets', 1: 'Card', 2: 'PayPal', 3: 'Other'}
    return d[v]
df['Pay_Method']=df['Pay_Method'].apply(paymethod)

def Browser_(v):
    d={0:'Chrome', 1:'Safari', 2:'Edge',3:'Other'}
    return d[v]
df['Browser']=df['Browser'].apply(Browser_)

"""# Pay Method and age group :"""

def agegroup(v):
    q=v//10
    r=v%10
    if r<5:
        return str(q*10)+'-'+str(q*10+5)
    else:
        return str(q*10+5)+'-'+str(q*10+10)

df['Age_group']=df['Age'].apply(agegroup)

"""# Questions

**Question1 What Age Group Buys from us the most ?**
"""

df['Age_group'].value_counts().sort_index().reset_index()

df['Age_group'].value_counts().sort_index().reset_index().plot(kind='bar',x='Age_group',y='count')

"""**Question2 What Payment Method is used most by Age_Groups**"""

ndf = df.groupby(['Pay_Method','Age_group']).agg(Total=('Pay_Method','count')).reset_index()
ndf

"""**Question3 What Browsers Our Customers use most ?**"""

df['Browser'].value_counts()

"""**Question4 Best Month For Sale**"""

df['Month']=df['Purchase_DATE'].dt.month_name()
df['Month_N']=df['Purchase_DATE'].dt.month
df['year']=df['Purchase_DATE'].dt.year
ndf=df.groupby(['Month_N','Month']).agg(
    Monthly_Qty=('Month_N','count'),
    Total_Sale=('Purchase_VALUE','sum'),
    Avg_sale=('Purchase_VALUE','mean')
).reset_index()
ndf

"""**Highest Orders In Months**"""

ndf.sort_values(['Monthly_Qty'],ascending=False).iloc[0,:]

""" **Highest** **Sale** **In** **Month**"""

ndf.sort_values(['Total_Sale'],ascending=False).iloc[0,:]

"""**What is the average time spent by male and female respectively on our Website ?**"""

df.groupby('Gender')['Time_Spent'].mean()

"""**Who are our Best Customers (Males Or Females ?)**"""

ndf3 = df.groupby('Gender').agg(

    Total_Revenue=('Revenue_Total', 'sum'),
    Average_Revenue=('Revenue_Total', 'mean'),
    Number_of_Purchases=('N_Purchases', 'mean'),
    Average_Time_Spent=('Time_Spent', 'mean')

).sort_values(by='Total_Revenue' , ascending=False).reset_index()
ndf3